### ISSUE TITLE
com.mux.stats.sdk.core.model.BaseQueryData.getMuxDictionary ANR triggered by slow operations in blamed thread

### ISSUE THREAD

**Issue by rajneeshrawal** [muxinc/mux-stats-sdk-media3#65]
Hello team,

I am using the below mux sdk:
implementation 'com.mux.stats.sdk.muxstats:data-media3:1.2.1'
 implementation "com.mux.stats.sdk.muxstats:data-media3-ima:1.2.1"
and in my application, an ANR is getting triggered by the mux SDK. Below is the ANR stack trace:

pool-25-thread-1 (runnable):tid=69 systid=5548 
       at java.lang.StringBuilder.append(StringBuilder.java:203)
       at org.json.JSONTokener.nextString(JSONTokener.java:360)
       at org.json.JSONTokener.nextValue(JSONTokener.java:428)
       at org.json.JSONObject.<init>(JSONObject.java:225)
       at org.json.JSONTokener.nextValue(JSONTokener.java:431)
       at org.json.JSONArray.<init>(JSONArray.java:124)
       at org.json.JSONTokener.nextValue(JSONTokener.java:434)
       at org.json.JSONObject.<init>(JSONObject.java:244)
       at org.json.JSONTokener.nextValue(JSONTokener.java:431)
       at org.json.JSONObject.<init>(JSONObject.java:244)
       at org.json.JSONObject.<init>(JSONObject.java:357)
       at com.mux.stats.sdk.core.model.BaseQueryData.getMuxDictionary(BaseQueryData.java:1)
       at com.mux.stats.sdk.core.trackers.BeaconBatchTracker.a(BeaconBatchTracker.java:117)
       at com.mux.stats.sdk.core.trackers.BeaconBatchTracker.a(BeaconBatchTracker.java:67)
       at com.mux.stats.sdk.core.trackers.BeaconBatchTracker.b(BeaconBatchTracker.java:22)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

main (blocked):tid=1 systid=29424 | waiting to lock <0x0586003a> (vf.e) held by thread 69
       at com.mux.stats.sdk.core.trackers.BeaconBatchTracker.e(BeaconBatchTracker.java:1)
       at com.mux.stats.sdk.core.trackers.BeaconBatchTracker.handle(BeaconBatchTracker.java:218)
       at com.mux.stats.sdk.core.CorePlayer.handle(CorePlayer.java:62)
       at com.mux.stats.sdk.core.Core$a.handle(Core.java:62)
       at com.mux.stats.sdk.core.events.EventBus.dispatch(EventBus.java:1)
       at com.mux.stats.sdk.core.CorePlayer.dispatch(CorePlayer.java:84)
       at com.mux.stats.sdk.core.events.RedispatchEventListener.handle(RedispatchEventListener.java:106)
       at com.mux.stats.sdk.core.events.EventBus.dispatch(EventBus.java:1)
       at com.mux.stats.sdk.core.CoreView.dispatch(CoreView.java:559)
       at com.mux.stats.sdk.core.trackers.BaseTracker.dispatch(BaseTracker.java:1)
       at com.mux.stats.sdk.core.trackers.ExternalEventTracker.handlePlaybackEvent(ExternalEventTracker.java:68)
       at com.mux.stats.sdk.core.trackers.BaseTracker.handle(BaseTracker.java:1)
       at com.mux.stats.sdk.core.events.EventBus.dispatch(EventBus.java:1)
       at com.mux.stats.sdk.core.CoreView.dispatch(CoreView.java:559)
       at com.mux.stats.sdk.core.CorePlayer.dispatch(CorePlayer.java:236)
       at com.mux.stats.sdk.core.Core.dispatchEventForPlayer(Core.java:109)
       at com.mux.stats.sdk.muxstats.MuxStats.a(MuxStats.java:45)
       at com.mux.stats.sdk.muxstats.MuxStats.handle(MuxStats.java:943)
       at com.mux.stats.sdk.core.events.EventBus.dispatch(EventBus.java:1)
       at com.mux.stats.sdk.muxstats.bandwidth.BandwidthMetricDispatcher.dispatch(BandwidthMetrics.kt:393)
       at com.mux.stats.sdk.muxstats.bandwidth.BandwidthMetricDispatcher.onLoadCompleted(BandwidthMetricDispatcher.java:339)
       at com.mux.stats.sdk.muxstats.MuxAnalyticsListener.onLoadCompleted(ExoPlayerBinding.kt:268)
       at androidx.media3.exoplayer.analytics.DefaultAnalyticsCollector.lambda$onLoadCompleted$26(DefaultAnalyticsCollector.java:427)
       at androidx.media3.common.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:339)
       at androidx.media3.common.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:223)
       at androidx.media3.common.util.ListenerSet.flushEvents(ListenerSet.java:245)
       at androidx.media3.common.util.ListenerSet.sendEvent(ListenerSet.java:260)
       at androidx.media3.exoplayer.analytics.DefaultAnalyticsCollector.sendEvent(DefaultAnalyticsCollector.java:903)
       at androidx.media3.exoplayer.analytics.DefaultAnalyticsCollector.onLoadCompleted(DefaultAnalyticsCollector.java:424)
       at androidx.media3.exoplayer.MediaSourceList$ForwardingEventListener.lambda$onLoadCompleted$1(MediaSourceList.java:591)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)

Kindly suggest how to  handle this ANR.

**Comment by daytime-em** [comment]
Hello!

Thank you for your report. We are investigating this issue and will reply with further updates.
